# Generated by Django 2.2 on 2023-06-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutMe', '0002_auto_20230619_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='hobby',
            name='img',
            field=models.CharField(default='https://steamuserimages-a.akamaihd.net/ugc/106232967022720363/48DED32DECDB08B6A6377E2AC750277BCF2330A0/', max_length=500),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img',
            field=models.CharField(default='https://steamuserimages-a.akamaihd.net/ugc/106232967022720363/48DED32DECDB08B6A6377E2AC750277BCF2330A0/', max_length=500),
        ),
    ]
