# Generated by Django 2.2 on 2023-06-26 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutMe', '0003_auto_20230626_1648'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Message',
        ),
    ]
